# Generated by Django 4.2.7 on 2023-11-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ativacao',
            options={'verbose_name': 'ativacao', 'verbose_name_plural': 'ativacoes'},
        ),
    ]
